name: 'GZoltar Feedback
description: 'Analyzes GZoltar results and posts a comment on the pull request.'
inputs:
  token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.
      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.
      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
  build-path:
    description: 'Path to the build/target directory containing the GZoltar results'
    default: '/build'
  ranking-files-path:
    description: 'Path to the directory containing the fault localization report files produced by GZoltar. Example: `/build/sfl/txt/`'
    default: '/build/sfl/txt/'
  serialized-coverage-file-path:
    description: 'Path to the file containing the serialized file with the coverage collect by GZoltar. Example: `/build/gzoltar.ser`'
    required: false
  test-cases-file-path:
    description: 'Path to the file containing a list of all test cases generated by GZoltar. Example: `/build/sfl/txt/tests.csv`'
    required: false
  spectra-file-path:
    description: 'Path to the file containing a list of all lines of code identified by GZoltar (one per row) of all classes under test. Example: `/build/sfl/txt/spectra.csv`'
    required: false
  matrix-file-path:
    description: 'Path to the file containing a binary coverage matrix produced by GZoltar. Example: `/build/sfl/txt/matrix.txt`'
    required: false
  sfl-ranking:
    description: 'List of the SFL ranking algorithms to use. Example: `[ochiai, tarantula]` (Keep in mind that each algorithm need to have present a fault localization report file in the `ranking-files-path` directory with his name, i.e. `ochiai.ranking.csv`.)'
    default: ['ochiai']
  statistics-file-path:
    description: 'Path to the file containing statistics information of the ranking produced by GZoltar. Example: `/build/sfl/txt/statistics.csv`'
    required: false
  upload-artifacts:
    description: 'Uploads the GZoltar results as an artifact'
    default: false
runs:
  using: 'node16'
  main: 'dist/index.js'